import {Notification} from "./class/Notification.class";
import {User} from "./class/User.class";
import {Email} from "./class/Email.class";
import util from "util";

const debuglog = util.debuglog('cron');

interface UserProp {
    id: number,
    userName: string,
    firebaseToken: string
}

export class Cron {
    constructor() {
    }

    static async init() {
        try {
            // const everydayRunAt7 = new CronOperation('0 0 19 * * *', sendPun);
            // everydayRunAt7.init();
            await sendEmail();
        } catch (err) {
            console.log('error', err);
            return err;
        }
    }
}

async function sendEmail(): Promise<void> {
    try {
        const email = new Email();
        const emailPayload = {
            personalizations:
                [{
                    to: [{email: 'shborade@gmail.com'}]
                }],
            from: {email: 'shubhankar@dirtcube.xyz', name: 'Capshot NodeJS'},
            subject: "Server Down!!!, Trending hashtag is not working",
            content: [{
                "type": "text/plain",
                "value": "Test Email\n\n-From Shubhankar Borade.\n\nThis is an autogenerated email. Please do not reply."
            }],
            reply_to: {email: 'shubhankar@dirtcube.xyz', name: 'Capshot NodeJS'},
        };
        const stringifyEmailPayload = JSON.stringify(emailPayload)
        const result = await email.sendEmail(stringifyEmailPayload);
        console.log('results', result);
        return
    } catch (err) {
        console.log('error', err);
    }
}

async function sendPun(): Promise<void> {
    try {
        // fetch the users who have android version code more than required
        const users: UserProp[] = await User.getUserOfAndroidVersionCode(153);
        const firebaseToken: string[] = users.map(user => user.firebaseToken);

        // send notification on 7 pm
        const notificationBody = Notification.getRandomPun('indians');
        for (let token of firebaseToken) {
            const notification = new Notification(token);
            await notification.sendNotification({
                title: 'Meme O\'Clock! ⏰',
                body: notificationBody,
                intent: 'notify'
            })
        }
    } catch (err) {
        console.log('error', err);
    }
}


